kind: Deployment
apiVersion: apps/v1
metadata:
  name: tfh-chatbot
  labels:
    app: tfh-chatbot
spec:
  replicas: 1
  selector:
    matchLabels:
      app: tfh-chatbot
  template:
    metadata:
      labels:
        app: tfh-chatbot
    spec:
      containers:
        - name: tfh-chatbot
          image: "sockmal/tfh-chatbot:0.6.0"
          ports:
          - containerPort: 8089
          env:
          - name: ENV_URI_BASE
            valueFrom:
              configMapKeyRef:
                name: tfh-chatbot-config
                key: uriBase
          livenessProbe:
            httpGet:
              path: /
              port: 8089
            initialDelaySeconds: 20
            periodSeconds: 3
          readinessProbe:
            httpGet:
              path: /
              port: 8089
            initialDelaySeconds: 5
            periodSeconds: 3
          resources:
            requests:
                memory: "256Mi"
                cpu: "500m"
            limits:
                memory: "512Mi"
                cpu: "900m"

---

kind: Service
apiVersion: v1
metadata:
  name: tfh-chatbot-service
spec:
  selector:
    app: tfh-chatbot
  ports:
    - port: 8089